compile: BuildingBoundState
BuildingBoundState:SetBoundStatesH1D.cpp
	g++ -O3 SetBoundStatesH1D.cpp /Users/achacon/Dropbox/Dropbox/CODE/qfishbowld001/cartesian.cpp -I /Users/achacon/Dropbox/Dropbox/CODE/qfishbowld001/include/ -w -lfftw3
